<input type="button" onclick="return false;" class="show_form" data-form-name="form_login_html" value="<?php echo $this->__('Login') ?>" style="display:none;" />
<input type="button" onclick="return false;" class="show_form" data-form-name="form_register_html" value="<?php echo $this->__('Register') ?>" />
<input type="button" onclick="return false;" class="show_form" data-form-name="form_forgot_password_html" value="<?php echo $this->__('Forgot Password') ?>" />






