<div class="page-title">
    <h1><?php echo $this->__('Forgot Your Password?') ?></h1>
</div>
<?php echo $this->getMessagesBlock()->toHtml() ?>

<div class="messages"></div>


<form action="<?php echo $this->getUrl('*/*/forgotpasswordpost') ?>" method="post" id="ajaxkit-forgotpassword-form-validate">
    <div class="fieldset">
        <h2 class="legend"><?php echo $this->__('Retrieve your password here') ?></h2>
        <p><?php echo $this->__('Please enter your email address below. You will receive a link to reset your password.') ?></p>
        <ul class="form-list">
            <li>
                <label for="email_address" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                <div class="input-box">
                    <input type="text" name="email" alt="email" id="email_address" class="input-text required-entry validate-email" value="<?php echo $this->escapeHtml($this->getEmailValue()) ?>" />
                </div>
            </li>
            <?php echo $this->getChildHtml('form.additional.info_forgotpassword'); ?>
        </ul>
    </div>

    <button onclick="return false;" class="ajaxkit-login-submit-form"  class="button" type="button"><span><span><?php echo $this->__('Send') ?></span></span></button>
</form>
