<div class="account-login">
    <div class="page-title">
        <h1><?php echo $this->__('Login or Create an Account') ?></h1>
    </div>

    <div class="messages"></div>

    <form action="<?php echo $this->getPostActionUrl() ?>" method="post" id="ajaxkit-login-form-validate">
        <div class="registered-users">
            <div class="content">
                <h2><?php echo $this->__('Registered Customers') ?></h2>
                <p><?php echo $this->__('If you have an account with us, please log in.') ?></p>
                <ul class="form-list">
                    <li>
                        <label for="email" class="required"><em>*</em><?php echo $this->__('Email Address') ?></label>
                        <div class="input-box">
                            <input type="text" name="login[username]" value="<?php echo $this->escapeHtml($this->getUsername()) ?>" id="email" class="input-text required-entry validate-email" title="<?php echo $this->__('Email Address') ?>" />
                        </div>
                    </li>
                    <li>
                        <label for="pass" class="required"><em>*</em><?php echo $this->__('Password') ?></label>
                        <div class="input-box">
                            <input value="" type="password" name="login[password]" class="input-text required-entry validate-password" id="pass" title="<?php echo $this->__('Password') ?>" />
                        </div>
                    </li>
                    <?php echo $this->getChildHtml('form.additional.info_login'); ?>


                    <?php echo $this->getChildHtml('persistent.remember.me_login'); ?>
                    <?php echo $this->getChildHtml('persistent.remember.me.tooltip_login'); ?>
                </ul>
                <p class="required"><?php echo $this->__('* Required Fields') ?></p>
            </div>
        </div>
        <button onclick="return false;" class="ajaxkit-login-submit-form"  class="button" type="button"><span><span><?php echo $this->__('Login') ?></span></span></button>
    </form>
</div>
