<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
?>
<?php 
echo $this->getLayout()->createBlock('cms/block')->setBlockId('our_popular_caegories')->toHtml(); 
echo $this->getLayout()->createBlock('cms/block')->setBlockId('compo_custom_yellow_footer')->toHtml(); 
?>
<!--<footer id="footer">-->
<footer class="footer">
    <article class="container">
	<?php echo $this->getLayout()->getMConfigResultByAlias('custom_footer_block'); ?>
</article>
</footer>
