<?php
/**
 * @package     compo
 * @copyright   Copyright (c) 2010-2015 MeigeeTeam. (http://www.meigeeteam.com)
 */
/**
 * @var Mage_Page_Block_Html_Header $this
 */
?>
<div class="header-wrapper">
<!--	<div class="checkpoint-wrapper">
        <div id="checkpoint-1"></div>
        </div>-->
	
        <header class="header">
        <div class="container">
            <div class="row">
                <div class="col-sm-3">
                    <div class="logo-wrapper">
                        <?php $logo = $this->getLayout()->getLogoData(false); ?>
                        <h2 class="logo">
                            <strong><?php echo $this->getLayout()->getLogoData(true) ?></strong>
                            <a href="<?php echo $this->getUrl('') ?>" title="<?php echo $this->getLayout()->getLogoData(true) ?>"> <img <?php echo $logo ?> alt="<?php echo $this->getLayout()->getLogoData(true) ?>"> </a>
                        </h2>
                    </div>
                </div>
                <div class="col-sm-9">
                    <?php
                    echo $this->getLayout()->createBlock('cms/block')->setBlockId('header-top-links')->toHtml(); 
                    ?>   
                    <div class="yd-hd-bottom">
                        <ul class="help-yd">
                            <li>
                                <a href="#">
                                    <img src="<?php echo $this->getSkinUrl('images/header-top-images/preedesignlook.png')?>" alt="Pre Dezined Looks" title="Pre Dezined Looks" width="25"/>PRE DEZINED LOOKS
                                </a>
                            </li>
                            <li>
                                <a href="#"><img src="<?php echo $this->getSkinUrl('images/header-top-images/pencil.png')?>" alt="Design Yourself" title="Design Yourself" width="25"/>Design it yourself
                                </a>
                            </li>
                        </ul>
                        <?php echo $this->getChildHtml('topSearch'); ?>
                    <a href="#" class="btn btn-love"><i class="fa fa-heart-o" aria-hidden="true"></i></a>
                    <!--<button type="button" class="btn btn-cart" data-toggle="modal" data-target="#myModal"><i class="fa fa-shopping-cart" aria-hidden="true"></i>&nbsp;&nbsp;<span>Cart (2)</span></button>-->    
                    <?php echo $this->getChildHtml('cart_sidebar'); ?>
                    <?php //echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/mobile_menu.phtml')->toHtml(); ?>
                    <?php //echo $this->getChildHtml('topMenu'); ?>
                    </div>

                </div>
            </div>
        </div>
    </header>
	<?php echo $this->getChildHtml('sticky_header'); ?>
	<?php echo $this->getChildHtml('topContainer'); ?>
	<?php echo $this->getChildHtml('meigee_loader'); ?>
	<?php echo $this->getChildHtml('before_content'); ?>
</div>
<?php echo $this->getLayout()->createBlock('core/template')->setTemplate('page/html/mobile_menu.phtml')->toHtml(); ?>
<?php echo $this->getChildHtml('topMenu'); ?>
